project:
  type: website

website:
  title: "Models of Choice and Forecasting"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css


