project:
  type: website
  output-dir: docs

website:
  title: "Models of Choice and Forecasting"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/robertwwalker/ChoiceAndForecasting
      - icon: twitter
        href: https://twitter.com/PieRatio
format:
  html:
    theme: solar
    css: styles.css


