<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robert W. Walker">
<meta name="dcterms.date" content="2022-09-12">

<title>Models of Choice and Forecasting - Week 3: Binomial Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta name="twitter:title" content="Models of Choice and Forecasting - Week 3: Binomial Logistic Regression">
<meta name="twitter:description" content="The slides are here.">
<meta name="twitter:image" content="https://quartopub.com/sites/rww/models-of-choice-and-forecasting/posts/week-3/image.png">
<meta name="twitter:creator" content="@PieRatio">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Models of Choice and Forecasting</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/robertwwalker/ChoiceAndForecasting"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/PieRatio"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Week 3: Binomial Logistic Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Robert W. Walker </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 12, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-skinny" id="toc-the-skinny" class="nav-link active" data-scroll-target="#the-skinny">The Skinny</a>
  <ul class="collapse">
  <li><a href="#overview-and-comments" id="toc-overview-and-comments" class="nav-link" data-scroll-target="#overview-and-comments">Overview and Comments</a></li>
  </ul></li>
  <li><a href="#my-notes-on-binary-glms" id="toc-my-notes-on-binary-glms" class="nav-link" data-scroll-target="#my-notes-on-binary-glms">My Notes on Binary GLMs</a></li>
  <li><a href="#generalized-linear-models" id="toc-generalized-linear-models" class="nav-link" data-scroll-target="#generalized-linear-models">Generalized Linear Models</a>
  <ul class="collapse">
  <li><a href="#a-probit-model" id="toc-a-probit-model" class="nav-link" data-scroll-target="#a-probit-model">A Probit Model</a>
  <ul class="collapse">
  <li><a href="#estimation-of-a-first-glm" id="toc-estimation-of-a-first-glm" class="nav-link" data-scroll-target="#estimation-of-a-first-glm">Estimation of a First GLM</a></li>
  <li><a href="#a-scaled-coefficient-plot" id="toc-a-scaled-coefficient-plot" class="nav-link" data-scroll-target="#a-scaled-coefficient-plot">A Scaled Coefficient Plot</a></li>
  <li><a href="#the-trouble-with-non-linear-models" id="toc-the-trouble-with-non-linear-models" class="nav-link" data-scroll-target="#the-trouble-with-non-linear-models">The Trouble with Non-linear Models</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic Regression</a></li>
  <li><a href="#other-binomial-glms" id="toc-other-binomial-glms" class="nav-link" data-scroll-target="#other-binomial-glms">Other Binomial GLMs</a></li>
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals">Residuals</a></li>
  <li><a href="#predicted-probability" id="toc-predicted-probability" class="nav-link" data-scroll-target="#predicted-probability">Predicted Probability</a></li>
  </ul></li>
  <li><a href="#a-better-businessy-way-of-thinking-about-all-of-this" id="toc-a-better-businessy-way-of-thinking-about-all-of-this" class="nav-link" data-scroll-target="#a-better-businessy-way-of-thinking-about-all-of-this">A Better (Businessy) Way of Thinking About all of This</a>
  <ul class="collapse">
  <li><a href="#quadratic-terms" id="toc-quadratic-terms" class="nav-link" data-scroll-target="#quadratic-terms">Quadratic Terms?</a></li>
  <li><a href="#a-final-note-a-classification-tree" id="toc-a-final-note-a-classification-tree" class="nav-link" data-scroll-target="#a-final-note-a-classification-tree">A final note: a classification tree</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>The slides <a href="https://robertwwalker.github.io/xaringan/CMF-Week-3/">are here.</a></p>
<p>Our third class meeting will focus on <a href="https://peopleanalytics-regression-book.org/bin-log-reg.html">Chapter 5</a> of <strong>Handbook of Regression Modeling in People Analytics</strong>.</p>
<section id="the-skinny" class="level1">
<h1>The Skinny</h1>
<p>Why not just use a linear model for a binary outcome? It turns out that you can but many people know just enough to think you don’t know what you are talking about if you do. In a very, very dense paper, Jamie Robins (1986, iirc) proves that, as long as the predicted probabilities tend to remain in the region of about 0.2 to 0.8, that is, <strong>as long as the model is not all that good</strong>, then it really doesn’t matter except that the standard errors you would estimate are likely incorrect. If the model is good for one or the other of the levels, then the behavior in the extremes matters; you could end up with predictions that are less than zero or greater than one and those are invalid as probabilities. Let’s just peak at this example. I will load some data on Churn. For details, <a href="https://www.kaggle.com/datasets/blastchar/telco-customer-churn">look on Kaggle.com – a great source of data</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Churn <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://github.com/robertwwalker/DADMStuff/raw/master/WA_Fn-UseC_-Telco-Customer-Churn.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Churn)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Churn<span class="sc">$</span>Churn)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "customerID"       "gender"           "SeniorCitizen"    "Partner"         
 [5] "Dependents"       "tenure"           "PhoneService"     "MultipleLines"   
 [9] "InternetService"  "OnlineSecurity"   "OnlineBackup"     "DeviceProtection"
[13] "TechSupport"      "StreamingTV"      "StreamingMovies"  "Contract"        
[17] "PaperlessBilling" "PaymentMethod"    "MonthlyCharges"   "TotalCharges"    
[21] "Churn"           

  No  Yes 
5174 1869 </code></pre>
</div>
</div>
<p>Now to a regression model. We will need a variable type change to pull this off. Let’s have a look at the necessary transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Churn<span class="sc">$</span>Churn)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(<span class="fu">as.factor</span>(Churn<span class="sc">$</span>Churn))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(<span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(Churn<span class="sc">$</span>Churn)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>Churn<span class="sc">$</span>Churn.Numeric <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.factor</span>(Churn<span class="sc">$</span>Churn))<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Churn<span class="sc">$</span>Churn.Numeric)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:7043] "No" "No" "Yes" "No" "Yes" "Yes" "No" "No" "Yes" "No" "No" ...
 Factor w/ 2 levels "No","Yes": 1 1 2 1 2 2 1 1 2 1 ...
 num [1:7043] 1 1 2 1 2 2 1 1 2 1 ...
 num [1:7043] 0 0 1 0 1 1 0 0 1 0 ...</code></pre>
</div>
</div>
<p><code>Churn</code> is a character variable. To turn it to a quantity taking values of zero and one, <code>as.factor()</code> turns the character variable <code>Churn</code> into a factor with two levels, No and Yes. <code>as.numeric()</code> turns this into a number, one or two. I then subtract one to get a variable that takes values zero or one and store it as <code>Churn.Numeric</code>. I will make Churn a function of a few chosen variables; there is more in the dataset that I could work with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE, warning=FALSE}</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer); <span class="fu">library</span>(magrittr); <span class="fu">library</span>(tidyverse); <span class="fu">library</span>(skimr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>my.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Churn.Numeric<span class="sc">~</span>InternetService<span class="sc">+</span>tenure<span class="sc">+</span>PhoneService<span class="sc">+</span>Contract<span class="sc">+</span>TotalCharges, <span class="at">data=</span>Churn)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my.lm)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Churn.Numeric ~ InternetService + tenure + PhoneService + 
    Contract + TotalCharges, data = Churn)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.64458 -0.26256 -0.07269  0.35565  1.12180 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 4.274e-01  1.651e-02  25.892  &lt; 2e-16 ***
InternetServiceFiber optic  2.601e-01  1.268e-02  20.512  &lt; 2e-16 ***
InternetServiceNo          -1.476e-01  1.588e-02  -9.290  &lt; 2e-16 ***
tenure                     -1.909e-03  4.642e-04  -4.112 3.97e-05 ***
PhoneServiceYes            -3.823e-02  1.769e-02  -2.161   0.0307 *  
ContractOne year           -1.385e-01  1.383e-02 -10.018  &lt; 2e-16 ***
ContractTwo year           -1.184e-01  1.641e-02  -7.218 5.81e-13 ***
TotalCharges               -3.961e-05  5.244e-06  -7.555 4.73e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3812 on 7024 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.2562,    Adjusted R-squared:  0.2554 
F-statistic: 345.6 on 7 and 7024 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Scientific notation can render tables hard to read. We can adjust R’s internal options to require more leading zeroes before scientific notation is used with <code>scipen</code> in options, e.g.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">6</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my.lm)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Churn.Numeric ~ InternetService + tenure + PhoneService + 
    Contract + TotalCharges, data = Churn)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.64458 -0.26256 -0.07269  0.35565  1.12180 

Coefficients:
                               Estimate   Std. Error t value Pr(&gt;|t|)    
(Intercept)                 0.427421784  0.016507683  25.892  &lt; 2e-16 ***
InternetServiceFiber optic  0.260067246  0.012678756  20.512  &lt; 2e-16 ***
InternetServiceNo          -0.147560579  0.015884435  -9.290  &lt; 2e-16 ***
tenure                     -0.001908716  0.000464227  -4.112 3.97e-05 ***
PhoneServiceYes            -0.038230897  0.017690283  -2.161   0.0307 *  
ContractOne year           -0.138502281  0.013825977 -10.018  &lt; 2e-16 ***
ContractTwo year           -0.118438811  0.016407760  -7.218 5.81e-13 ***
TotalCharges               -0.000039614  0.000005244  -7.555 4.73e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3812 on 7024 degrees of freedom
  (11 observations deleted due to missingness)
Multiple R-squared:  0.2562,    Adjusted R-squared:  0.2554 
F-statistic: 345.6 on 7 and 7024 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>That is much easier to read. The first thing to note is that there are lots of stars. The model seems to <code>explain variance</code> in the outcome with all the caveats that go with that idea for a 0/1 variable. For example, about 25% of the variance in <code>Churn</code> can be accounted for by these predictors. The model F-statistic assessing the joint hypothesis that all predictors have zero slopes yields an absolutely enormous statistic; the observed F-value is 345.6; 99% of F values with 7 numerator and 7024 denominator degrees of freedom are less than 2.64; a statistic this large is quite unlikely by chance. Moreover, each of the individual t-statistics are greater than 2 in absolute value. Those are the encouraging parts. The residual standard error should give us pause; on average, we are 0.38 away from the observed outcome in the probability metric. That is not great though to make it smaller, the model would have to predict in the extremes. Now, let me put this into a nice table.</p>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', warning=FALSE, message=FALSE}</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(my.lm, <span class="at">type=</span><span class="st">"html"</span>, <span class="at">style=</span><span class="st">"apsr"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<table style="text-align:center">
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
Churn.Numeric
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceFiber optic
</td>
<td>
0.260<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.013)
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceNo
</td>
<td>
-0.148<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.016)
</td>
</tr>
<tr>
<td style="text-align:left">
tenure
</td>
<td>
-0.002<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0005)
</td>
</tr>
<tr>
<td style="text-align:left">
PhoneServiceYes
</td>
<td>
-0.038<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.018)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractOne year
</td>
<td>
-0.139<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.014)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractTwo year
</td>
<td>
-0.118<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.016)
</td>
</tr>
<tr>
<td style="text-align:left">
TotalCharges
</td>
<td>
-0.00004<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00001)
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.427<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.017)
</td>
</tr>
<tr>
<td style="text-align:left">
N
</td>
<td>
7,032
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.256
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.255
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.381 (df = 7024)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
345.603<sup>***</sup> (df = 7; 7024)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td colspan="2" style="text-align:left">
<sup><em></em></sup><em>p &lt; .1; <sup><strong></strong></sup><strong>p &lt; .05; <sup></sup></strong></em>p &lt; .01
</td>
</tr>

</tbody></table>
<p>Let’s return to my original criticism of using this particular model and assuming that the outcome is a quantity when it only takes two values. Are all of the predictions well-behaved?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>my.lm<span class="sc">$</span>fitted.values <span class="sc">%&gt;%</span> <span class="fu">skim</span>()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">7032</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">data</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: left;">▆▇▇▇▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>No, there are negative values. To prevent that, we need a different tool; this is the subject of Chapter 5.</p>
<p>We should also examine residuals. Using a variety of tests of linear model assumptions, we find the model lacking in every one but constant variance [homo/heteroscedasticity].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gvlma)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gvlma</span>(my.lm)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Churn.Numeric ~ InternetService + tenure + PhoneService + 
    Contract + TotalCharges, data = Churn)

Coefficients:
               (Intercept)  InternetServiceFiber optic  
                0.42742178                  0.26006725  
         InternetServiceNo                      tenure  
               -0.14756058                 -0.00190872  
           PhoneServiceYes            ContractOne year  
               -0.03823090                 -0.13850228  
          ContractTwo year                TotalCharges  
               -0.11843881                 -0.00003961  


ASSESSMENT OF THE LINEAR MODEL ASSUMPTIONS
USING THE GLOBAL TEST ON 4 DEGREES-OF-FREEDOM:
Level of Significance =  0.05 

Call:
 gvlma(x = my.lm) 

                     Value   p-value                   Decision
Global Stat        630.599 0.000e+00 Assumptions NOT satisfied!
Skewness           377.348 0.000e+00 Assumptions NOT satisfied!
Kurtosis            64.207 1.110e-15 Assumptions NOT satisfied!
Link Function      187.439 0.000e+00 Assumptions NOT satisfied!
Heteroscedasticity   1.605 2.051e-01    Assumptions acceptable.</code></pre>
</div>
</div>
<p>A linear model seems not to work well for these data. Models designed for this task will occupy our attention after a few notes and an overview.</p>
<section id="overview-and-comments" class="level2">
<h2 class="anchored" data-anchor-id="overview-and-comments">Overview and Comments</h2>
<p>What we require is a regression type tool tuned to represent data drawn from a generic binomial distribution. There are actually a few such models that I will introduce you to. There are also some really interesting models that you can fit that build mixtures of the different approaches but we won’t go that far. I should also note that there is a whole class of models on binary classification using trees. If you remember regression trees, you can also build regression trees for binary problems. I will do a bit of this in the end. Before that, some initial observations:</p>
<ul>
<li>I am using <code>stargazer</code> to produce the tables; they are nice and easy to produce. They have raw html output so I can embed that directly using <code>asis</code> in the code chunks and typesetting to html.<br>
</li>
<li>This whole document makes use of <code>fenced</code> code chunks. You can copy and paste this into a new markdown or quarto to play along with the ticks built in.<br>
</li>
<li>If one wants to omit a chunk at the top, you would do it with the bracketed part adding option <code>include=FALSE</code>. I always suppress warnings and messages to read (surrounded by curly brackets) <em>r setup, include=FALSE</em>. If you use this option and load libraries, readers will find it hard to figure out how commands may have changed meaning by masking.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">warning=</span><span class="cn">FALSE</span>, <span class="at">message=</span><span class="cn">FALSE</span>, <span class="at">tidy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">9119</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="my-notes-on-binary-glms" class="level1">
<h1>My Notes on Binary GLMs</h1>
<p>Suppose we have some variable that we want to explain, say <code>Churn</code> that has two mutually exclusive and exhaustive alternatives. <strong>Customers can either Churn or not</strong>. Any given customer is conceptualized as a Bernoulli trial, e.g.&nbsp;<span class="math inline">\(\pi^{y}(1-\pi)^{1-y}\)</span>. With a willingness to believe that every <code>Churn</code> decision is an independently and identically distributed trial in this group of customers, overall churn is a binomial random variable with probability mass function <span class="math display">\[P_{y} = {n \choose y} \pi^{y}(1-\pi)^{n-y}\]</span> where</p>
<ul>
<li><span class="math inline">\(P_{y}\)</span> is the binomial probability of <span class="math inline">\(y\)</span></li>
<li><span class="math inline">\(y\)</span> is the number of successes in <span class="math inline">\(n\)</span> trials</li>
<li><span class="math inline">\(n\)</span> is the number of trials</li>
<li><span class="math inline">\(\pi\)</span> is the probability of success in any given trial.</li>
</ul>
<p>That’s just a fancy way of saying that we have a binomial distribution on our hands. This is known as the <strong>canonical</strong> distribution for binary data because <span class="math inline">\(\pi\)</span> is a sufficient statistic – a complete characterization of Churn because it only takes two values. The challenge is that we wish to formulate a regression model for <span class="math inline">\(\pi\)</span> which will first require that we to grips with the existence of <span class="math inline">\(\pi_{i}\)</span>.</p>
</section>
<section id="generalized-linear-models" class="level1">
<h1>Generalized Linear Models</h1>
<p>I need some model that is bounded to zero and one, abstractly, because probabilities are subject to a sum to one constraint. This is where there is some diversity in the representations; let me explain. In generalized linear models, there are two keys to the specification: the family and the link. We have already covered the family; it has to be binomial.</p>
<p>In the theory of these models, presented by Peter McCullagh and John Nelder in 1989<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, that link for the probabilities is what ties regression to the binomial distribution; we posit that <span class="math inline">\((1-\pi_{i}) = Pr(y_{i}=1|X_{i}) = 1-F(X_{i}\beta)\)</span> so that <span class="math inline">\(\pi_{i} = Pr(y_{i}=0|X_{i})= F(X_{i}\beta)\)</span>. If <span class="math inline">\(F\)</span> is some well-behaved probability distribution, then the aforementioned is valid. There are a few ways of actually writing that; the <span class="math inline">\(\pi_{i}\)</span> could be derived from a normal distribution – called probit –, the distribution that the text focuses on is, the logistic distribution – the model is named logit–, and there are a few others that are somewhat common: the Cauchy, the log-log, and the complimentary log-log. The latter two are asymmetric and mirrors one of the other. What we want to do is to find the estimates of <span class="math inline">\(\beta\)</span> that maximize the likelihood of the sample we observe.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<section id="a-probit-model" class="level2">
<h2 class="anchored" data-anchor-id="a-probit-model">A Probit Model</h2>
<p>First, a little substitution and some notation. Let me label the normal probability up to <span class="math inline">\(X_{i}\beta\)</span> to be <span class="math inline">\(\Phi(X\beta)\)</span> and the probability above <span class="math inline">\(X\beta\)</span> to be <span class="math inline">\(1-\Phi(X+{i}\beta)\)</span>. I could substitute this into the binomial and obtain the product for the entire sample – this is known as the likelihood.</p>
<p><span class="math display">\[\prod^{n}_{i=1} \Phi(X_{i}\beta)^{1-y_{i}}(1-\Phi(X_{i}\beta))^{y_{i}}\]</span></p>
<p>Taking logs yields:</p>
<p><span class="math display">\[\ln \mathcal{L} =  \sum^{n}_{i=1} (1-y_{i})\ln \Phi(X_{i}\beta) + y_{i} \ln (1-\Phi(X_{i}\beta))\]</span></p>
<p>So the solution becomes</p>
<p><span class="math display">\[\arg \max_{\beta} \ln \mathcal{L} =  \arg \max_{\beta} \sum^{n}_{i=1} (1-y_{i})\ln \Phi(X_{i}\beta) + y_{i} \ln (1-\Phi(X_{i}\beta))\]</span></p>
<p>In English, we want to find the values of <span class="math inline">\(\beta\)</span> that maximize the log-likelihod of the entire sample.</p>
<section id="estimation-of-a-first-glm" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-a-first-glm">Estimation of a First GLM</h3>
<p>Now to another example with the same measure of <code>Churn</code>. The outcome of interest is <code>Churn</code>. The model specification will call <code>glm</code>, let me examine <code>Churn</code> as a function of <code>InternetService</code>, <code>tenure</code>, <code>PhoneService</code>, <code>Contract</code> and <code>TotalCharges</code>. There is one trick to deploying it, the outcome variable must be a <code>factor</code> type. To make the table nice, let me mutate the type to a factor and then we can model it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, message=FALSE}</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Churn <span class="sc">%&lt;&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">ChurnF =</span> <span class="fu">as.factor</span>(Churn))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>Churn <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(Churn, ChurnF) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">as.numeric</span>(ChurnF)) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>()</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Churn ChurnF as.numeric(ChurnF)
1    No     No                  1
2    No     No                  1
3   Yes    Yes                  2
4    No     No                  1
5   Yes    Yes                  2
6   Yes    Yes                  2</code></pre>
</div>
</div>
<p>Now I want to estimate the model and have a look at the result. I will put this in a stargazer table.</p>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', warning=FALSE, message=FALSE}</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>my.probit <span class="ot">&lt;-</span> <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>), <span class="at">data =</span> Churn)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(my.probit, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">style =</span> <span class="st">"apsr"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<table style="text-align:center">
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
ChurnF
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceFiber optic
</td>
<td>
0.726<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.053)
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceNo
</td>
<td>
-0.458<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.070)
</td>
</tr>
<tr>
<td style="text-align:left">
tenure
</td>
<td>
-0.028<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
PhoneServiceYes
</td>
<td>
-0.372<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.073)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractOne year
</td>
<td>
-0.489<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.057)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractTwo year
</td>
<td>
-0.866<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.083)
</td>
</tr>
<tr>
<td style="text-align:left">
TotalCharges
</td>
<td>
0.0001<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00003)
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.131<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.069)
</td>
</tr>
<tr>
<td style="text-align:left">
N
</td>
<td>
7,032
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-3,019.439
</td>
</tr>
<tr>
<td style="text-align:left">
AIC
</td>
<td>
6,054.878
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td colspan="2" style="text-align:left">
<sup><em></em></sup><em>p &lt; .1; <sup><strong></strong></sup><strong>p &lt; .05; <sup></sup></strong></em>p &lt; .01
</td>
</tr>

</tbody></table>
<p>We can do <code>astrology</code> on the tables; read the stars. Fiber optic customers are more likely to Churn and those without internet service are less likely to Churn but both conditions are compared to a third category absorbed into the Constant. What is that category?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>janitor<span class="sc">::</span><span class="fu">tabyl</span>(Churn<span class="sc">$</span>InternetService)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn$InternetService    n   percent
                   DSL 2421 0.3437456
           Fiber optic 3096 0.4395854
                    No 1526 0.2166690</code></pre>
</div>
</div>
<p><code>DSL</code> subscribers. It is the first in alphabetical order. <em>That is the default option.</em> That also means that the constant captures those on Month-to-month contracts and without phone service – the omitted category for each. So what do these <code>coefficients</code> show?</p>
<p>The slopes represent the effect of a one-unit change in <span class="math inline">\(x\)</span> on the underlying distribution for the probabilities. Unless one has intuition for those distributions, they come across as nonsensical. In the table above, let me take the example of tenure. For each unit of tenure [another month having been a customer], the normal variable <span class="math inline">\(Z \sim N(0,1)\)</span> decreases by 0.028. But what that means depends on whether we are going from 0 to -0.028 or from -2 to -2.028. Remember the standard normal has about 95% of probability between -2 and 2 and has a modal/most common value at zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">Z =</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(.) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> Z) <span class="sc">+</span> <span class="fu">geom_density</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="sc">-</span><span class="fl">2.028</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="sc">-</span><span class="dv">2</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="sc">-</span><span class="fl">0.028</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="dv">0</span>), <span class="at">color =</span> <span class="st">"blue"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The associated probabilities in that example would be either small or nearly trivial even over 1000s of customers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">2.028</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">0</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">0.028</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001470008
[1] 0.01116892</code></pre>
</div>
</div>
<p>It seems like most scholars I run across don’t actually know this; they tend to stick to stars (That’s why your book plays with odds and logistic regression but I want to start here because y’all have never seen the logistic distribution, except on my poster….) Before that, here’s another way of showing the actual estimated slopes even if their intuition is hard.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_summs</span>(my.probit, <span class="at">inner_ci_level =</span> <span class="fl">0.95</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I can make that plot better.</p>
</section>
<section id="a-scaled-coefficient-plot" class="level3">
<h3 class="anchored" data-anchor-id="a-scaled-coefficient-plot">A Scaled Coefficient Plot</h3>
<p>Remember scaling from last time and linear models? No rules against that. The two metric variables – <code>tenure</code> and <code>TotalCharges</code> – are now the change in Z for a <strong>one standard deviation</strong> change in the relevant variable. That’s 2267 dollars for <code>TotalCharges</code> and 24.6 months for <code>tenure</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Churn <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">skim</span>(TotalCharges, tenure)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">7043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TotalCharges</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2283.30</td>
<td style="text-align: right;">2266.77</td>
<td style="text-align: right;">18.8</td>
<td style="text-align: right;">401.45</td>
<td style="text-align: right;">1397.47</td>
<td style="text-align: right;">3794.74</td>
<td style="text-align: right;">8684.8</td>
<td style="text-align: left;">▇▂▂▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">tenure</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">32.37</td>
<td style="text-align: right;">24.56</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: right;">55.00</td>
<td style="text-align: right;">72.0</td>
<td style="text-align: left;">▇▃▃▃▆</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Churn <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">tenure =</span> <span class="fu">scale</span>(tenure), <span class="at">TotalCharges =</span> <span class="fu">scale</span>(TotalCharges)) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>), <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot_summs</span>(., <span class="at">inner_ci_level =</span> <span class="fl">0.95</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What the plot makes clear is that basically all of the predictors are deemed important in Churn decisions by conventional standards as all have a very low probability of no relationship/zero slope. But that’s as far as we can get with these unless our audience shares this intuition for probability distributions.</p>
</section>
<section id="the-trouble-with-non-linear-models" class="level3">
<h3 class="anchored" data-anchor-id="the-trouble-with-non-linear-models">The Trouble with Non-linear Models</h3>
<p>I should be clear that the model does have lines; they are just lines inside of a nonlinear function – the F. The <code>generalized linear</code> part means that the interpretation of any one factor will depend on the values of the others. We will have to usually want to generate hypothetical data to understand what is really going on. After a presentation of the remaining models, I will return to my preferred method of interpretation.</p>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<p>The logistic distribution is the focus of the textbook chapter. To respecify the model using that, the only change in syntax is the <code>link</code>, we need it to be <code>link="logit"</code> which is the default.</p>
<p>The logistic function is given by:</p>
<p><span class="math display">\[\Lambda = \frac{e^{X\beta}}{1+e^{X\beta}}\]</span></p>
<p>But the rest is the same; it takes the very general representation and provides a specific probability function for <span class="math inline">\(F\)</span>:</p>
<p><span class="math display">\[\arg \max_{\beta} \ln \mathcal{L} =  \arg \max_{\beta} \sum^{n}_{i=1} (1-y_{i})\ln \Lambda(X_{i}\beta) + y_{i} \ln (1-\Lambda(X_{i}\beta))\]</span></p>
<p>One of the advantages of using the logistic distribution is that you can analytically solve it with only categorical variables. The other is the interpretation of the estimates; the slope is an increment in the log-odds, e.g.&nbsp;<span class="math inline">\(\ln (\frac{\pi_{y=1}}{1-\pi_{y=1}})\)</span>.</p>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', warning=FALSE, message=FALSE}</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>my.logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), <span class="at">data =</span> Churn)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(my.logit, my.probit, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">style =</span> <span class="st">"apsr"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<table style="text-align:center">
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
ChurnF
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
logistic
</td>
<td>
probit
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceFiber optic
</td>
<td>
1.172<sup>***</sup>
</td>
<td>
0.726<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.091)
</td>
<td>
(0.053)
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceNo
</td>
<td>
-0.765<sup>***</sup>
</td>
<td>
-0.458<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.127)
</td>
<td>
(0.070)
</td>
</tr>
<tr>
<td style="text-align:left">
tenure
</td>
<td>
-0.063<sup>***</sup>
</td>
<td>
-0.028<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.006)
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
PhoneServiceYes
</td>
<td>
-0.714<sup>***</sup>
</td>
<td>
-0.372<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.126)
</td>
<td>
(0.073)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractOne year
</td>
<td>
-0.874<sup>***</sup>
</td>
<td>
-0.489<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.103)
</td>
<td>
(0.057)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractTwo year
</td>
<td>
-1.781<sup>***</sup>
</td>
<td>
-0.866<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.172)
</td>
<td>
(0.083)
</td>
</tr>
<tr>
<td style="text-align:left">
TotalCharges
</td>
<td>
0.0004<sup>***</sup>
</td>
<td>
0.0001<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0001)
</td>
<td>
(0.00003)
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.373<sup>***</sup>
</td>
<td>
0.131<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.117)
</td>
<td>
(0.069)
</td>
</tr>
<tr>
<td style="text-align:left">
N
</td>
<td>
7,032
</td>
<td>
7,032
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-3,004.328
</td>
<td>
-3,019.439
</td>
</tr>
<tr>
<td style="text-align:left">
AIC
</td>
<td>
6,024.656
</td>
<td>
6,054.878
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td colspan="3" style="text-align:left">
<sup><em></em></sup><em>p &lt; .1; <sup><strong></strong></sup><strong>p &lt; .05; <sup></sup></strong></em>p &lt; .01
</td>
</tr>

</tbody></table>
<p>If we see these in a side by side comparison, it is obvious that the <code>logistic</code> version is bigger in absolute value across the board. So what do these mean in terms of actual odds of Churn or not?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(my.logit<span class="sc">$</span>coefficients)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               (Intercept) InternetServiceFiber optic 
                 1.4521830                  3.2282235 
         InternetServiceNo                     tenure 
                 0.4652907                  0.9393570 
           PhoneServiceYes           ContractOne year 
                 0.4898382                  0.4173338 
          ContractTwo year               TotalCharges 
                 0.1685345                  1.0003559 </code></pre>
</div>
</div>
<p>All else equal,</p>
<ul>
<li>The odds of Churning with Fiber optics, as opposed to DSL, increase by 223%.</li>
<li>The odds of Churning with No internet, as opposed to DSL, decrease by 53.5% .</li>
<li>The odds of Churning with No phone service, as opposed to Phone service, are 51% lower.</li>
<li>The odds of Churning decrease by 4% per unit tenure [month].</li>
<li>The odds of Churning increase by 0.04% per dollar of total charges.</li>
<li>The odds of Churning decrease under contracts. Compared to none, about 83% lower odds under a two-year contract and 58% lower odds under a one-year contract.</li>
</ul>
<p>If you choose to work with odds, then the suggestion to exponentiate the confidence intervals for the odds-ratios is sound.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(my.logit))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               2.5 %    97.5 %
(Intercept)                1.1535576 1.8288933
InternetServiceFiber optic 2.7035580 3.8611249
InternetServiceNo          0.3619193 0.5951803
tenure                     0.9284409 0.9500587
PhoneServiceYes            0.3822153 0.6276984
ContractOne year           0.3400210 0.5101487
ContractTwo year           0.1190988 0.2338910
TotalCharges               1.0002350 1.0004795</code></pre>
</div>
</div>
<p>There are diagnostics that can be applied to these models. The various pseudo-<span class="math inline">\(r^2\)</span> measures. This model fit is neither terrible nor good.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>DescTools<span class="sc">::</span><span class="fu">PseudoR2</span>(my.logit, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">"McFadden"</span>, <span class="st">"CoxSnell"</span>, <span class="st">"Nagelkerke"</span>, <span class="st">"Tjur"</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  McFadden   CoxSnell Nagelkerke       Tjur 
 0.2621401  0.2618213  0.3817196  0.2798359 </code></pre>
</div>
</div>
<p>Taking advantage of the book’s example, I first need to clean up the data, there are a few missing values. Then let me estimate the regression and diagnose it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>Churn.CC <span class="ot">&lt;-</span> Churn <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(ChurnF, InternetService, tenure, PhoneService, Contract, TotalCharges) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(TotalCharges))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>my.logit.CC <span class="ot">&lt;-</span> <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    TotalCharges, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>), <span class="at">data =</span> Churn.CC)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LogisticDx)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># get range of goodness-of-fit diagnostics</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>model_diagnostics <span class="ot">&lt;-</span> LogisticDx<span class="sc">::</span><span class="fu">gof</span>(my.logit.CC, <span class="at">plotROC =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>One very common plot for binary logistic regression is the ROC: the Receiver Operating Curve. It plots specificity against sensitivity. Specificity is the ability, in this case, to correctly identify non-Churners[few false positives is highly specific]; sensitivity is the ability of the test to correctly identify Churners [few false negatives is highly sensitive]. A useful mnemonic is that the presence of the letter <code>f</code> in specificity is a reminder that the False test results are False for the condition, while the <code>t</code> in sensitivity is True test results are True for the condition. Now, turning to the actual provided diagnostics, what all is in there? <code>?gof</code> for example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># returns a list</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(model_diagnostics)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>model_diagnostics<span class="sc">$</span>gof</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ct"    "chiSq" "ctHL"  "gof"   "R2"    "auc"  
         test  stat       val df         pVal
1:         HL chiSq 31.832686  8 9.979186e-05
2:        mHL     F 16.436041  9 4.896337e-27
3:       OsRo     Z  3.282456 NA 1.029070e-03
4: SstPgeq0.5     Z  6.656484 NA 2.804560e-11
5:   SstPl0.5     Z  5.983933 NA 2.178133e-09
6:    SstBoth chiSq 80.116227  2 4.008504e-18
7: SllPgeq0.5 chiSq 45.280618  1 1.707304e-11
8:   SllPl0.5 chiSq 29.794958  1 4.802393e-08
9:    SllBoth chiSq 54.741365  2 1.297369e-12</code></pre>
</div>
</div>
<p>This is not a very good model. It fails all the tests. We need to add more predictors; I have those but let’s keep it simple for now. Let me look at two more.</p>
</section>
<section id="other-binomial-glms" class="level2">
<h2 class="anchored" data-anchor-id="other-binomial-glms">Other Binomial GLMs</h2>
<p>The others</p>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', warning=FALSE, message=FALSE}</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>my.cauchit <span class="ot">&lt;-</span> <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"cauchit"</span>), <span class="at">data =</span> Churn)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>my.cloglogit <span class="ot">&lt;-</span> <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    TotalCharges, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"cloglog"</span>), <span class="at">data =</span> Churn)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(my.cauchit, my.cloglogit, my.logit, my.probit, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">style =</span> <span class="st">"apsr"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<table style="text-align:center">
<tbody><tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="4">
ChurnF
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
glm: binomial
</td>
<td>
glm: binomial
</td>
<td>
logistic
</td>
<td>
probit
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
link = cauchit
</td>
<td>
link = cloglog
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceFiber optic
</td>
<td>
0.993<sup>***</sup>
</td>
<td>
0.877<sup>***</sup>
</td>
<td>
1.172<sup>***</sup>
</td>
<td>
0.726<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.094)
</td>
<td>
(0.071)
</td>
<td>
(0.091)
</td>
<td>
(0.053)
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceNo
</td>
<td>
-0.790<sup>***</sup>
</td>
<td>
-0.640<sup>***</sup>
</td>
<td>
-0.765<sup>***</sup>
</td>
<td>
-0.458<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.174)
</td>
<td>
(0.112)
</td>
<td>
(0.127)
</td>
<td>
(0.070)
</td>
</tr>
<tr>
<td style="text-align:left">
tenure
</td>
<td>
-0.123<sup>***</sup>
</td>
<td>
-0.059<sup>***</sup>
</td>
<td>
-0.063<sup>***</sup>
</td>
<td>
-0.028<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.011)
</td>
<td>
(0.005)
</td>
<td>
(0.006)
</td>
<td>
(0.003)
</td>
</tr>
<tr>
<td style="text-align:left">
PhoneServiceYes
</td>
<td>
-0.705<sup>***</sup>
</td>
<td>
-0.586<sup>***</sup>
</td>
<td>
-0.714<sup>***</sup>
</td>
<td>
-0.372<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.136)
</td>
<td>
(0.099)
</td>
<td>
(0.126)
</td>
<td>
(0.073)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractOne year
</td>
<td>
-1.190<sup>***</sup>
</td>
<td>
-0.767<sup>***</sup>
</td>
<td>
-0.874<sup>***</sup>
</td>
<td>
-0.489<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.166)
</td>
<td>
(0.092)
</td>
<td>
(0.103)
</td>
<td>
(0.057)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractTwo year
</td>
<td>
-7.065<sup>***</sup>
</td>
<td>
-1.696<sup>***</sup>
</td>
<td>
-1.781<sup>***</sup>
</td>
<td>
-0.866<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1.254)
</td>
<td>
(0.161)
</td>
<td>
(0.172)
</td>
<td>
(0.083)
</td>
</tr>
<tr>
<td style="text-align:left">
TotalCharges
</td>
<td>
0.001<sup>***</sup>
</td>
<td>
0.0004<sup>***</sup>
</td>
<td>
0.0004<sup>***</sup>
</td>
<td>
0.0001<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
<td>
(0.0001)
</td>
<td>
(0.00003)
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.590<sup>***</sup>
</td>
<td>
-0.024
</td>
<td>
0.373<sup>***</sup>
</td>
<td>
0.131<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.122)
</td>
<td>
(0.088)
</td>
<td>
(0.117)
</td>
<td>
(0.069)
</td>
</tr>
<tr>
<td style="text-align:left">
N
</td>
<td>
7,032
</td>
<td>
7,032
</td>
<td>
7,032
</td>
<td>
7,032
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-2,997.445
</td>
<td>
-2,991.982
</td>
<td>
-3,004.328
</td>
<td>
-3,019.439
</td>
</tr>
<tr>
<td style="text-align:left">
AIC
</td>
<td>
6,010.891
</td>
<td>
5,999.964
</td>
<td>
6,024.656
</td>
<td>
6,054.878
</td>
</tr>
<tr>
<td colspan="5" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td colspan="5" style="text-align:left">
<sup><em></em></sup><em>p &lt; .1; <sup><strong></strong></sup><strong>p &lt; .05; <sup></sup></strong></em>p &lt; .01
</td>
</tr>

</tbody></table>
<p>The best fit seems to be provided by the <code>cloglog</code> distribution which is asymmetric.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(my.cloglogit, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(Churn.CC<span class="sc">$</span>ChurnF, predicted, <span class="at">plot =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.8386</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="residuals" class="level2">
<h2 class="anchored" data-anchor-id="residuals">Residuals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">density</span>(<span class="fu">residuals</span>(my.logit, <span class="st">"pearson"</span>))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(d, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is rather poor.</p>
</section>
<section id="predicted-probability" class="level2">
<h2 class="anchored" data-anchor-id="predicted-probability">Predicted Probability</h2>
<p>I find that the most straightforward way to interpret them is with plots in the probability metric. Let me take the example of <code>tenure</code>.</p>
<p>I will need to create data for interpretation. Let’s suppose we have a <code>DSL</code> user with phone service on a two year contract with average <code>TotalCharges</code>. The last thing I need to know is what values of <code>tenure</code> to show.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>Churn <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(InternetService <span class="sc">==</span> <span class="st">"DSL"</span>, PhoneService <span class="sc">==</span> <span class="st">"Yes"</span>, Contract <span class="sc">==</span> <span class="st">"Two year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">skim</span>(tenure, TotalCharges)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">467</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tenure</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">60.52</td>
<td style="text-align: right;">14.79</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">55.00</td>
<td style="text-align: right;">66.00</td>
<td style="text-align: right;">71.00</td>
<td style="text-align: right;">72.00</td>
<td style="text-align: left;">▁▁▁▂▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">TotalCharges</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">4733.47</td>
<td style="text-align: right;">1382.51</td>
<td style="text-align: right;">130.5</td>
<td style="text-align: right;">3867.24</td>
<td style="text-align: right;">4913.88</td>
<td style="text-align: right;">5879.86</td>
<td style="text-align: right;">6859.05</td>
<td style="text-align: left;">▁▂▅▇▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now I can create the data and generate predictions in the probability metric of the response.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>Tenure.Pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">InternetService =</span> <span class="st">"DSL"</span>, <span class="at">PhoneService =</span> <span class="st">"Yes"</span>, <span class="at">Contract =</span> <span class="st">"Two year"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">TotalCharges =</span> <span class="fl">4733.5</span>, <span class="at">tenure =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">72</span>, <span class="at">by =</span> <span class="dv">1</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>Tenure.Pred<span class="sc">$</span>Prob.Churn <span class="ot">&lt;-</span> <span class="fu">predict</span>(my.logit, <span class="at">newdata =</span> Tenure.Pred, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let me plot it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tenure.Pred) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> tenure, <span class="at">y =</span> Prob.Churn) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We could get fancier, too.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>Tenure.Pred.Three <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">data.frame</span>(<span class="at">InternetService =</span> <span class="st">"DSL"</span>, <span class="at">PhoneService =</span> <span class="st">"Yes"</span>,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Contract =</span> <span class="st">"Month-to-month"</span>, <span class="at">TotalCharges =</span> <span class="fl">4733.5</span>, <span class="at">tenure =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">72</span>, <span class="at">by =</span> <span class="dv">1</span>)),</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">InternetService =</span> <span class="st">"DSL"</span>, <span class="at">PhoneService =</span> <span class="st">"Yes"</span>, <span class="at">Contract =</span> <span class="st">"One year"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">TotalCharges =</span> <span class="fl">4733.5</span>, <span class="at">tenure =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">72</span>, <span class="at">by =</span> <span class="dv">1</span>)), <span class="fu">data.frame</span>(<span class="at">InternetService =</span> <span class="st">"DSL"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">PhoneService =</span> <span class="st">"Yes"</span>, <span class="at">Contract =</span> <span class="st">"Two year"</span>, <span class="at">TotalCharges =</span> <span class="fl">4733.5</span>, <span class="at">tenure =</span> <span class="fu">seq</span>(<span class="dv">0</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>            <span class="dv">72</span>, <span class="at">by =</span> <span class="dv">1</span>)))</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>Tenure.Pred.Three<span class="sc">$</span>Prob.Churn <span class="ot">&lt;-</span> <span class="fu">predict</span>(my.logit, <span class="at">newdata =</span> Tenure.Pred.Three, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tenure.Pred.Three) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> tenure, <span class="at">y =</span> Prob.Churn, <span class="at">color =</span> Contract) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Pr(Churn)"</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="a-better-businessy-way-of-thinking-about-all-of-this" class="level1">
<h1>A Better (Businessy) Way of Thinking About all of This</h1>
<p>I personally believe that the only real way to assess models for use in <strong>predictive analytics</strong> is to assess them by that criteria. That doesn’t mean fitting inside the extant sample of data, but rather sampling from it and then using the model to predict what is known as a <strong>holdout sample</strong>. Let me show you what I mean. In this case, let me use the probit and logit models from before and a 75/25 split. This means that I will analyse 75 percent and predict the other 25 percent. I can use <code>join</code> style commands to pull it off pretty simply. I have 7043 rows. So I want 5283 rows of the original data out of that 7043.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> Churn[<span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">7043</span>), <span class="at">size =</span> <span class="dv">5283</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>), ]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> Churn <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">anti_join</span>(., train)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now to estimate the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>mod.train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>), <span class="at">data =</span> .)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now to predict the result on the <code>test</code> set that I created. I will then turn the probabilities into a best guess by whether <code>Churn</code> or <code>No</code> is more likely.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Pred.Probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.train, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Pred.Val =</span> (Pred.Probs <span class="sc">&gt;</span> <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    janitor<span class="sc">::</span><span class="fu">tabyl</span>(Churn, Pred.Val, <span class="at">show_na =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_percentages</span>(<span class="st">"row"</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn     FALSE      TRUE
    No 0.8961749 0.1038251
   Yes 0.5042017 0.4957983</code></pre>
</div>
</div>
<p>Then all of the totals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Pred.Val =</span> (Pred.Probs <span class="sc">&gt;</span> <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    janitor<span class="sc">::</span><span class="fu">tabyl</span>(Churn, Pred.Val, <span class="at">show_na =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_totals</span>(<span class="fu">c</span>(<span class="st">"row"</span>, <span class="st">"col"</span>))</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn FALSE TRUE Total
    No  1148  133  1281
   Yes   240  236   476
 Total  1388  369  1757</code></pre>
</div>
</div>
<p>Now you might say that the fact we can only get 50 to 55 percent of <code>Churn='Yes'</code> with the model, remember that only 26.5 percent of people <code>Churn</code> overall so we have improved quite a bit over knowing nothing at all but the raw row probability. In this specific case, the probability of <code>Yes</code> in the test set is shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tabyl</span>(Churn)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn    n   percent
    No 1284 0.7295455
   Yes  476 0.2704545</code></pre>
</div>
</div>
<section id="quadratic-terms" class="level2">
<h2 class="anchored" data-anchor-id="quadratic-terms">Quadratic Terms?</h2>
<p>What would happen if I assume that the effect of <code>tenure</code> is not a line but instead has some curvature.</p>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, results='asis', warning=FALSE, message=FALSE}</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>mod.train.SQ <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">glm</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> <span class="fu">I</span>(tenure<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>        TotalCharges, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>), <span class="at">data =</span> .)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(mod.train, mod.train.SQ, <span class="at">type =</span> <span class="st">"html"</span>, <span class="at">style =</span> <span class="st">"apsr"</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<table style="text-align:center">
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
ChurnF
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceFiber optic
</td>
<td>
0.703<sup>***</sup>
</td>
<td>
0.761<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.061)
</td>
<td>
(0.062)
</td>
</tr>
<tr>
<td style="text-align:left">
InternetServiceNo
</td>
<td>
-0.520<sup>***</sup>
</td>
<td>
-0.566<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.082)
</td>
<td>
(0.083)
</td>
</tr>
<tr>
<td style="text-align:left">
tenure
</td>
<td>
-0.030<sup>***</sup>
</td>
<td>
-0.043<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.004)
</td>
<td>
(0.004)
</td>
</tr>
<tr>
<td style="text-align:left">
I(tenure2)
</td>
<td>
</td>
<td>
0.0003<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.0001)
</td>
</tr>
<tr>
<td style="text-align:left">
PhoneServiceYes
</td>
<td>
-0.296<sup>***</sup>
</td>
<td>
-0.262<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.085)
</td>
<td>
(0.085)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractOne year
</td>
<td>
-0.467<sup>***</sup>
</td>
<td>
-0.465<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.067)
</td>
<td>
(0.067)
</td>
</tr>
<tr>
<td style="text-align:left">
ContractTwo year
</td>
<td>
-0.927<sup>***</sup>
</td>
<td>
-1.067<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.100)
</td>
<td>
(0.105)
</td>
</tr>
<tr>
<td style="text-align:left">
TotalCharges
</td>
<td>
0.0001<sup>***</sup>
</td>
<td>
0.00005
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.00004)
</td>
<td>
(0.00004)
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
0.086
</td>
<td>
0.171<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.081)
</td>
<td>
(0.082)
</td>
</tr>
<tr>
<td style="text-align:left">
N
</td>
<td>
5,275
</td>
<td>
5,275
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-2,235.094
</td>
<td>
-2,220.230
</td>
</tr>
<tr>
<td style="text-align:left">
AIC
</td>
<td>
4,486.189
</td>
<td>
4,458.460
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td colspan="3" style="text-align:left">
<sup><em></em></sup><em>p &lt; .1; <sup><strong></strong></sup><strong>p &lt; .05; <sup></sup></strong></em>p &lt; .01
</td>
</tr>

</tbody></table>
<p>As we can see from the table, the curvature appears to be different from zero though interpreting such a thing ceteris paribus is probably nonsense. Maybe better to see what happens in the metric of the predicted probability. Let me recycle the prediction data I used to draw this in the earlier section. What would the two predictions look like and how do they differ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>Tenure.Pred<span class="sc">$</span>Prob.Churn<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.train, <span class="at">newdata =</span> Tenure.Pred, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>Tenure.Pred<span class="sc">$</span>Prob.Churn.Sq <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.train.SQ, <span class="at">newdata =</span> Tenure.Pred, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Tenure.Pred) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> tenure, <span class="at">y =</span> Prob.Churn.Sq) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Prob.Churn<span class="fl">.2</span>),</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Pr(Churn)"</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now let’s predict for the test set, does it really do better?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Pred.Probs.Sq <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod.train, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Pred.Val.Sq =</span> (Pred.Probs.Sq <span class="sc">&gt;</span> <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    janitor<span class="sc">::</span><span class="fu">tabyl</span>(Churn, Pred.Val.Sq, <span class="at">show_na =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">adorn_percentages</span>(<span class="st">"row"</span>)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn     FALSE      TRUE
    No 0.8961749 0.1038251
   Yes 0.5042017 0.4957983</code></pre>
</div>
</div>
<p>Not usually. Such people are really unlikely to Churn no matter what; it only starts at about 0.25.</p>
</section>
<section id="a-final-note-a-classification-tree" class="level2">
<h2 class="anchored" data-anchor-id="a-final-note-a-classification-tree">A final note: a classification tree</h2>
<p>First, I will start with a generic classification tree with everything set to the defaults. Then I will look at a report to refine it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>fit.BT <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit.BT)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>How well does it fit the test sample?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Churn.No <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit.BT, <span class="at">newdata =</span> test)[, <span class="dv">1</span>]</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Churn.PredRT <span class="ot">&lt;-</span> (test<span class="sc">$</span>Churn.No <span class="sc">&lt;</span> <span class="fl">0.5</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tabyl</span>(Churn, Churn.PredRT)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn FALSE TRUE
    No  1210   74
   Yes   319  157</code></pre>
</div>
</div>
<p>Not very well. We can alter the tolerance for complexity using some diagnostics about the tree.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">printcp</span>(fit.BT)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart(formula = ChurnF ~ InternetService + tenure + PhoneService + 
    Contract + TotalCharges, data = train, method = "class")

Variables actually used in tree construction:
[1] Contract        InternetService tenure         

Root node error: 1393/5283 = 0.26368

n= 5283 

        CP nsplit rel error  xerror     xstd
1 0.056712      0   1.00000 1.00000 0.022991
2 0.010000      3   0.78177 0.78823 0.021172</code></pre>
</div>
</div>
<p>The option <code>cp</code> controls a complexity parameter that keeps the tree from overfitting the tree. I want to show a fairly complex one so I will change from the default of 0.01 to 0.0025.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>fit.BT<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">rpart</span>(ChurnF <span class="sc">~</span> InternetService <span class="sc">+</span> tenure <span class="sc">+</span> PhoneService <span class="sc">+</span> Contract <span class="sc">+</span> TotalCharges,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"class"</span>, <span class="at">cp =</span> <span class="fl">0.0025</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(fit.BT<span class="fl">.2</span>, <span class="at">extra =</span> <span class="dv">106</span>)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Churn.No <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit.BT<span class="fl">.2</span>, <span class="at">newdata =</span> test)[, <span class="dv">1</span>]</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>Churn.PredRT2 <span class="ot">&lt;-</span> (test<span class="sc">$</span>Churn.No <span class="sc">&lt;</span> <span class="fl">0.5</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>test <span class="sc">%&gt;%</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tabyl</span>(Churn, Churn.PredRT2)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Churn FALSE TRUE
    No  1154  130
   Yes   251  225</code></pre>
</div>
</div>
<p>In this case, we have 1379 correct with the big tree and 1367 right with the smaller tree.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>McCullagh, P. and Nelder, J.A. (1989) <strong>Generalized Linear Models. 2nd Edition</strong>, Chapman and Hall, London. <a href="http://dx.doi.org/10.1007/978-1-4899-3242-6">http://dx.doi.org/10.1007/978-1-4899-3242-6</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Full disclosure, I am cheating a bit here. I don’t really want to explain the fitting of generalized linear models as it most often involves iteratively reweighted least squares. I prefer to motivate them with the far more intuitive likelihood approach though they are not, strictly speaking, identical.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>