<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Robert W. Walker">
<meta name="dcterms.date" content="2022-09-05">

<title>Models of Choice and Forecasting - Week 2: Inference and Regression: A Review</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<meta name="twitter:title" content="Models of Choice and Forecasting - Week 2: Inference and Regression: A Review">
<meta name="twitter:description" content="The slides are here.. The video is linked here.">
<meta name="twitter:image" content="https://quartopub.com/sites/rww/models-of-choice-and-forecasting/posts/week-2/image.jpg">
<meta name="twitter:creator" content="@PieRatio">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Models of Choice and Forecasting</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/robertwwalker/ChoiceAndForecasting"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/PieRatio"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Week 2: Inference and Regression: A Review</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Robert W. Walker </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 5, 2022</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>The slides <a href="https://robertwwalker.github.io/xaringan/CMF-Week-2/">are here.</a>. The video is <a href="https://youtu.be/gwgD4pF-Qt8">linked here</a>.</p>
<p>Our second class meeting will focus on <a href="https://peopleanalytics-regression-book.org/gitbook/found-stats.html">Chapter 3</a>; and <a href="https://peopleanalytics-regression-book.org/gitbook/linear-reg-ols.html">Chapter 4</a> of <strong>Handbook of Regression Modeling in People Analytics</strong> for next time.</p>
<section id="chapter-3" class="level1">
<h1>Chapter 3</h1>
<section id="hypothesis-tests-and-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-tests-and-confidence-intervals">Hypothesis Tests and Confidence Intervals</h2>
<section id="single-means-with-the-cars-data" class="level3">
<h3 class="anchored" data-anchor-id="single-means-with-the-cars-data">Single means with the cars data</h3>
<p>I will work with R’s internal dataset on cars: <code>cars</code>. There are two variables in the dataset, this is what they look like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/cars-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="an-hypothesis-test" class="level2">
<h2 class="anchored" data-anchor-id="an-hypothesis-test">An Hypothesis Test</h2>
<p>I will work with the speed variable. The hypothesis to advance is that 17 or greater is the true average speed. The alternative must then be that the average speed is less than 17. Knowing only the sample size, I can figure out what <span class="math inline">\(t\)</span> must be to reject 17 or greater and conclude that the true average must be less with 90% probability. The sample mean would have to be at least <code>qt(0.1, 49)</code> standard errors below 17 to rule out a mean of 17 or greater. Now let’s see what we have. Let me skim the data for the relevant information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">cars</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">speed</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.40</td>
<td style="text-align: right;">5.29</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">▂▅▇▇▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">dist</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">42.98</td>
<td style="text-align: right;">25.77</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">120</td>
<td style="text-align: left;">▅▇▅▂▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Doing the math by hand, I get:</p>
<p><span class="math display">\[ t = \frac{\overline{x} - \mu}{\frac{s}{\sqrt{n}}} = \frac{15.4 - 17}{\frac{5.29}{\sqrt{50}}} = -2.14 \]</span></p>
<p>Interpreting the result, the sample mean is 2.14 standard errors below the hypothetical mean of 17. The probability of a sample mean of 15.4 [or smaller] given a true average of 17, this standard deviation and sample size is <code>pt(-2.14, 49)</code> = 0.0186798. Notice that probability is less than 0.1; thus with at least 90% confidence, the true mean is not 17 or greater and thus must be smaller. Assuming the hypothetical mean [17 or greater] is true, the likelihood of generating a sample mean of 15.4 is only 0.0187 and this is far less than the 10% permissible outside of 90% confidence. Indeed, any sample mean more than 1.299 standard errors below 17 would be too small to sustain the belief that the true mean is 17 or greater because <code>qt(0.1, 49)</code> is -1.299. Put in the original metric, any sample mean below 16.0285747 would require a rejection of the claim that the true mean is 17 or greater with 90% confidence.</p>
</section>
<section id="the-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="the-confidence-interval">The Confidence Interval</h2>
<p>The confidence interval is always centered on the sample mean. Rearranging the equation above and solving for <span class="math inline">\(\mu\)</span> given the <span class="math inline">\(t\)</span> above, we get</p>
<p><span class="math display">\[ \mu = \overline{x} - t(\frac{s}{\sqrt{n}}) = 15.4 - (-1.299*\frac{5.29}{\sqrt{50}}) = 16.37143 \]</span></p>
<p>With 90% confidence, given this sample mean, the true value should be less than 16.37143.</p>
</section>
<section id="the-native-t.test" class="level2">
<h2 class="anchored" data-anchor-id="the-native-t.test">The native <code>t.test</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cars<span class="sc">$</span>speed, <span class="at">conf.level =</span> <span class="fl">0.9</span>, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu=</span><span class="dv">17</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  cars$speed
t = -2.1397, df = 49, p-value = 0.01869
alternative hypothesis: true mean is less than 17
90 percent confidence interval:
     -Inf 16.37143
sample estimates:
mean of x 
     15.4 </code></pre>
</div>
</div>
</section>
<section id="simplifying" class="level2">
<h2 class="anchored" data-anchor-id="simplifying">Simplifying?</h2>
<p><span class="math display">\[ t(\frac{s}{\sqrt{n}}) = \overline{x} - \mu \]</span> can lead to either:</p>
<p><span class="math display">\[  \overline{x} - t(\frac{s}{\sqrt{n}}) = \mu \]</span></p>
<p>or</p>
<p><span class="math display">\[ \overline{x} = \mu + t(\frac{s}{\sqrt{n}}) \]</span></p>
<p>So a minus <span class="math inline">\(t\)</span> will be below <span class="math inline">\(\mu\)</span> but above <span class="math inline">\(\overline{x}\)</span> and a positive <span class="math inline">\(t\)</span> will be above <span class="math inline">\(\mu\)</span> but below <span class="math inline">\(\overline{x}\)</span>.<br>
1. An hypothesis test given <span class="math inline">\(\mu\)</span> with an alternative that is less must then render an upper bound given <span class="math inline">\(\overline{x}\)</span>.<br>
2. An hypothesis test given <span class="math inline">\(\mu\)</span> with an alternative that is greater must then render a lower bound given <span class="math inline">\(\overline{x}\)</span>.</p>
</section>
<section id="a-graphical-representation" class="level2">
<h2 class="anchored" data-anchor-id="a-graphical-representation">A graphical representation</h2>
<p>Given a sample size <span class="math inline">\(n\)</span>, some unknown constant <span class="math inline">\(\mu\)</span> and satisfaction of Lindeberg’s condition, the sampling distribution of the sample mean follows a <span class="math inline">\(t\)</span> distribution with degrees of freedom <span class="math inline">\(n-1\)</span>. To render a graphical representation, let’s arbitrarily set n to 50, as in the above example. Here is a plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"x-bar -"</span>,mu,<span class="st">" (measured in std. errors of the mean)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="inverting-the-scale-transformation" class="level3">
<h3 class="anchored" data-anchor-id="inverting-the-scale-transformation">Inverting the <code>scale</code> transformation</h3>
<p>We can now reverse the scale by the standard error of the mean. In the above example, it is 0.7478. Measured in miles per hour, we obtain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"x-bar -"</span>,mu,<span class="st">" (measured in mph)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now we will take the concrete example above.</p>
</section>
<section id="the-hypothesis-test" class="level3">
<h3 class="anchored" data-anchor-id="the-hypothesis-test">The Hypothesis Test</h3>
<p>We claim that the true mean is 17 or greater. Now we need center the distribution above as though the claim is true.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span><span class="dv">17</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(mu,<span class="st">" (measured in mph)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">17</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">17</span><span class="sc">+</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="dv">21</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>)), <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The sample mean is estimated to be 15.4. How likely is that?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span><span class="dv">17</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"x-bar -"</span>,mu,<span class="st">" (measured in mph)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">17</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">15.4</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">17</span><span class="sc">+</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="dv">21</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>)), <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">17</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="fl">2.14</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="fl">2.14</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="dv">0</span>), <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">col=</span><span class="st">"black"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">17</span> <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.1</span>, <span class="at">df=</span><span class="dv">49</span>)<span class="sc">*</span><span class="fl">0.7874</span>, <span class="at">col=</span><span class="st">"black"</span>, <span class="at">lty=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The probability of seeing such a small sample mean if the true average is 17 is only 0.01869. The probability above the dotted black line is 0.9 with 0.1 below. WIth 90% confidence, anything below this would be sufficient evidence to reject the claim that the true average is 17 or above.</p>
</section>
</section>
<section id="the-confidence-interval-1" class="level2">
<h2 class="anchored" data-anchor-id="the-confidence-interval-1">The Confidence Interval</h2>
<p>Let’s take the sample mean as the center and work out a confidence interval at 90%. It’s exactly the 16.37143 gives above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span><span class="fl">15.4</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(mu,<span class="st">" | x-bar (measured in mph)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">15.4</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">15.4</span> <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.1</span>, <span class="at">df=</span><span class="dv">49</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="at">col=</span><span class="st">"black"</span>, <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="fl">15.4</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="fl">1.3</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="fl">1.3</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="dv">0</span>), <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As an aside, 17 has exactly 0.01869 probability above it shown in orange.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span><span class="fl">15.4</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(mu,<span class="st">" | x-bar (measured in mph)"</span>, <span class="at">sep=</span><span class="st">""</span>)), <span class="at">ylab=</span><span class="st">"Density"</span>, <span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">15.4</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">15.4</span> <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.1</span>, <span class="at">df=</span><span class="dv">49</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="at">col=</span><span class="st">"black"</span>, <span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="fl">15.4</span><span class="sc">+</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="fl">1.3</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fu">dt</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="fl">1.3</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="dv">0</span>), <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">15.4</span><span class="sc">+</span><span class="fu">seq</span>(<span class="fl">2.14</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>)<span class="sc">*</span><span class="fl">0.7478</span>, <span class="dv">17</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fu">dt</span>(<span class="fu">seq</span>(<span class="fl">2.14</span>,<span class="dv">5</span>, <span class="at">by=</span><span class="fl">0.01</span>), <span class="at">df=</span><span class="dv">49</span>), <span class="dv">0</span>), <span class="at">col =</span> <span class="st">"orange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="chapter-4-linear-regression" class="level1">
<h1>Chapter 4: Linear Regression</h1>
<p>A linear regression example. The data can be loaded from the web.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if needed, download ugtests data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"http://peopleanalytics-regression-book.org/data/ugtests.csv"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ugtests <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ugtests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   975 obs. of  4 variables:
 $ Yr1  : int  27 70 27 26 46 86 40 60 49 80 ...
 $ Yr2  : int  50 104 36 75 77 122 100 92 98 127 ...
 $ Yr3  : int  52 126 148 115 75 119 125 78 119 67 ...
 $ Final: int  93 207 175 125 114 159 153 84 147 80 ...</code></pre>
</div>
</div>
<p>There are 975 individuals graduating in the past three years from the biology department of a large academic institution. We have data on four examinations:</p>
<ul>
<li>a first year exam ranging from 0 to 100 (Yr1)</li>
<li>a second year exam ranging from 0 to 200 (Yr2)</li>
<li>a third year exam ranging from 0 to 200 (Yr3)</li>
<li>a Final year exam ranging from 0 to 300 (Final)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr); <span class="fu">library</span>(kableExtra)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(ugtests) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(skim_type<span class="sc">==</span><span class="st">"numeric"</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> skim_type </th>
   <th style="text-align:left;"> skim_variable </th>
   <th style="text-align:right;"> n_missing </th>
   <th style="text-align:right;"> complete_rate </th>
   <th style="text-align:right;"> numeric.mean </th>
   <th style="text-align:right;"> numeric.sd </th>
   <th style="text-align:right;"> numeric.p0 </th>
   <th style="text-align:right;"> numeric.p25 </th>
   <th style="text-align:right;"> numeric.p50 </th>
   <th style="text-align:right;"> numeric.p75 </th>
   <th style="text-align:right;"> numeric.p100 </th>
   <th style="text-align:left;"> numeric.hist </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Yr1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 52.14564 </td>
   <td style="text-align:right;"> 14.92408 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 42 </td>
   <td style="text-align:right;"> 53 </td>
   <td style="text-align:right;"> 62 </td>
   <td style="text-align:right;"> 99 </td>
   <td style="text-align:left;"> ▁▃▇▅▁ </td>
  </tr>
  <tr>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Yr2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 92.39897 </td>
   <td style="text-align:right;"> 30.03847 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 94 </td>
   <td style="text-align:right;"> 112 </td>
   <td style="text-align:right;"> 188 </td>
   <td style="text-align:left;"> ▁▅▇▃▁ </td>
  </tr>
  <tr>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Yr3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 105.12103 </td>
   <td style="text-align:right;"> 33.50705 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 81 </td>
   <td style="text-align:right;"> 105 </td>
   <td style="text-align:right;"> 130 </td>
   <td style="text-align:right;"> 198 </td>
   <td style="text-align:left;"> ▁▅▇▅▁ </td>
  </tr>
  <tr>
   <td style="text-align:left;"> numeric </td>
   <td style="text-align:left;"> Final </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 148.96205 </td>
   <td style="text-align:right;"> 44.33966 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 118 </td>
   <td style="text-align:right;"> 147 </td>
   <td style="text-align:right;"> 175 </td>
   <td style="text-align:right;"> 295 </td>
   <td style="text-align:left;"> ▁▅▇▃▁ </td>
  </tr>
</tbody>
</table>

</div>
</div>
<section id="a-visual-of-the-data" class="level2">
<h2 class="anchored" data-anchor-id="a-visual-of-the-data">A Visual of the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># display a pairplot of all four columns of data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>GGally<span class="sc">::</span><span class="fu">ggpairs</span>(ugtests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>my.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Final <span class="sc">~</span> Yr1 <span class="sc">+</span> Yr2 <span class="sc">+</span> Yr3, <span class="at">data=</span>ugtests)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Final ~ Yr1 + Yr2 + Yr3, data = ugtests)

Residuals:
    Min      1Q  Median      3Q     Max 
-92.638 -20.349   0.001  18.954  98.489 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 14.14599    5.48006   2.581  0.00999 ** 
Yr1          0.07603    0.06538   1.163  0.24519    
Yr2          0.43129    0.03251  13.267  &lt; 2e-16 ***
Yr3          0.86568    0.02914  29.710  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30.43 on 971 degrees of freedom
Multiple R-squared:  0.5303,    Adjusted R-squared:  0.5289 
F-statistic: 365.5 on 3 and 971 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %     97.5 %
(Intercept)  3.39187185 24.9001071
Yr1         -0.05227936  0.2043318
Yr2          0.36749170  0.4950791
Yr3          0.80850142  0.9228610</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
 82.77839 173.39734 159.84579 148.02242 115.77826 176.31713 168.52573 125.90895 
        9        10        11        12        13        14        15        16 
163.15331 133.00197 128.01391 168.83298 167.28471 178.01432 162.81842 183.81939 
       17        18        19        20        21        22        23        24 
143.96109 175.00126 148.29571 183.06708 157.92531 119.95460 165.18879 178.26106 
       25        26        27        28        29        30        31        32 
193.06715 166.52931 200.39004 182.94018 181.82752 104.19713 146.86195 158.59539 
       33        34        35        36        37        38        39        40 
137.30246 155.14171 147.59592 188.38693 149.46722 189.57199 165.36883 207.92058 
       41        42        43        44        45        46        47        48 
158.81869 145.13679 127.04145 184.89905 223.48248 190.68129 105.91152 188.47370 
       49        50        51        52        53        54        55        56 
169.91737 125.98673 179.91299 155.57364  94.78176 107.90209 142.01859 127.27405 
       57        58        59        60        61        62        63        64 
143.04734  90.43469 115.62032 186.36874 164.78997 182.04486 138.72937 173.80034 
       65        66        67        68        69        70        71        72 
162.81500 110.89761 157.53103 171.04054 164.29372 151.36275 203.73632 133.85978 
       73        74        75        76        77        78        79        80 
158.14239 145.03931 114.09836 136.39042 150.19917  99.56150 145.66277 116.39753 
       81        82        83        84        85        86        87        88 
124.72053 138.48918 167.84005 102.19417 187.51815 148.69592 199.82845 146.45894 
       89        90        91        92        93        94        95        96 
123.73077 134.25546 133.56188 171.39099 148.68036 160.00402 141.50056 143.96279 
       97        98        99       100       101       102       103       104 
126.22552 146.13759 160.82167 168.19393 139.15162 126.63646 142.87183 209.15707 
      105       106       107       108       109       110       111       112 
161.60200 169.65369 101.21716 132.64506 133.35245  98.58109 104.99919 122.47906 
      113       114       115       116       117       118       119       120 
132.50088 135.04371 169.26422 156.66084 201.79068 102.50589 222.36274 137.85639 
      121       122       123       124       125       126       127       128 
117.81825  92.61602 166.14124  90.81172 155.28613 221.52163 117.23941 125.32530 
      129       130       131       132       133       134       135       136 
154.28567 125.02463 149.23229 188.75433 167.65071 141.48812 148.73942 128.18946 
      137       138       139       140       141       142       143       144 
173.30410 113.50085 146.77068 144.70245 143.32800 172.42426 146.83111 161.80039 
      145       146       147       148       149       150       151       152 
155.74509 121.45958 120.19341 196.55029 107.52819 145.84903 129.87730  84.26017 
      153       154       155       156       157       158       159       160 
147.22201 172.38103 148.90671 191.37033  92.95881 113.93839 115.32834 217.95006 
      161       162       163       164       165       166       167       168 
109.04391 182.47442 173.66693 143.54644 213.24494 154.53040 157.99341 168.20918 
      169       170       171       172       173       174       175       176 
142.79439 111.22351 169.00364  95.59458 200.50023 150.77458 103.15936 136.32932 
      177       178       179       180       181       182       183       184 
152.35701 121.13371 116.24995 172.44290 105.74986 144.68854 142.16437 103.03841 
      185       186       187       188       189       190       191       192 
 84.20453 124.65866 175.16434 181.48777 183.17732 166.12881 109.68631 149.19871 
      193       194       195       196       197       198       199       200 
148.99240 123.27911 156.46977 111.37381 133.40676 105.70352 178.22203 162.98116 
      201       202       203       204       205       206       207       208 
 88.71579 142.38459 126.29081 195.54808 121.88463 175.31327 171.16320 128.80527 
      209       210       211       212       213       214       215       216 
157.38069 144.47601 145.67519 157.45049  90.83488 125.04501 117.56217 166.65784 
      217       218       219       220       221       222       223       224 
142.60365 151.28361 138.80714 152.33864 177.32217 135.09624 169.95920 161.33378 
      225       226       227       228       229       230       231       232 
150.99366 167.63206 102.71562 110.43832 159.52327 151.78922 158.52699 186.41680 
      233       234       235       236       237       238       239       240 
124.74060 118.60478 162.54510 198.55014 123.77119 209.05134 207.10887 110.39340 
      241       242       243       244       245       246       247       248 
139.38280 168.02915 166.40038 219.52660 144.11283 160.18067 182.99728 151.63440 
      249       250       251       252       253       254       255       256 
152.04702 175.37858 153.20573 193.75934 142.24807 204.76959 147.85201  91.68673 
      257       258       259       260       261       262       263       264 
178.87067 164.06869 167.01479 172.92703 123.77229 175.05272 117.60429 111.97751 
      265       266       267       268       269       270       271       272 
159.97603 166.63812 173.31198 207.68459 140.66875 135.57418 176.71423 170.00300 
      273       274       275       276       277       278       279       280 
170.04457 177.26620 133.02378 146.19662 166.87042 163.96474 156.38611 160.34511 
      281       282       283       284       285       286       287       288 
 71.51067 192.31939  89.27563 146.58132 139.44811 105.11565  79.53330 121.12299 
      289       290       291       292       293       294       295       296 
110.14355 178.41312 158.55532 181.01467 203.41524 207.36041 108.01030 173.06385 
      297       298       299       300       301       302       303       304 
146.09265 128.71230 116.85816 216.44539 169.53445 124.77337 164.95305 190.56794 
      305       306       307       308       309       310       311       312 
129.06273 142.52591  95.61497 171.09510 188.31374  93.51730 117.69757 121.30134 
      313       314       315       316       317       318       319       320 
178.57730 157.74528 170.68833 120.24799 116.37542 164.43192 175.61114 220.06158 
      321       322       323       324       325       326       327       328 
181.74555 160.98583  86.27842 195.97205 136.46895 102.86908 220.53640 125.83914 
      329       330       331       332       333       334       335       336 
186.27545 176.93132 178.40037 148.32790 181.84927 133.17072 167.12163 191.16061 
      337       338       339       340       341       342       343       344 
167.95000 211.35983 163.46813  96.61852 151.47610 139.82344 138.38826 176.47513 
      345       346       347       348       349       350       351       352 
106.40781 158.88878 179.08940 148.79682 143.06119  93.72813 134.88542 153.31118 
      353       354       355       356       357       358       359       360 
116.84713 186.85398 177.47107 142.76953 163.52582 167.98283 177.39367 213.53039 
      361       362       363       364       365       366       367       368 
161.02175 129.52203 179.97033 161.03589 136.94095 127.20454 159.24064 152.34627 
      369       370       371       372       373       374       375       376 
188.04240 190.15391 181.43039 132.62329 167.16688 157.13535 200.36373 123.08217 
      377       378       379       380       381       382       383       384 
 95.83962 182.55975 167.50830  76.89241 140.75411 116.13802 108.41218 171.20843 
      385       386       387       388       389       390       391       392 
108.95821 159.18156 148.49892 109.31069 139.47722 178.64745 165.07685 175.29912 
      393       394       395       396       397       398       399       400 
157.02854 160.68996 198.45546 120.21546 148.23662 146.56264 168.47318 172.63256 
      401       402       403       404       405       406       407       408 
199.19678 148.82619 111.56629 159.27455  77.41079 130.80692 104.47776 175.76773 
      409       410       411       412       413       414       415       416 
146.68981 136.07840 196.72408 116.78047 108.14538 140.87229 104.28901 220.51154 
      417       418       419       420       421       422       423       424 
124.22878 120.27876 150.89275 160.30190 125.30044 130.61268 165.22609 182.98173 
      425       426       427       428       429       430       431       432 
197.48268 127.15171 137.72440 138.36959 189.30688 131.46424 120.45398 126.79471 
      433       434       435       436       437       438       439       440 
159.92036 106.12099 145.96688 199.03398 200.80264  91.66356 207.26604 120.99236 
      441       442       443       444       445       446       447       448 
134.59685 186.49729 125.37228  91.33883 215.94567 113.12211 140.71538 183.96527 
      449       450       451       452       453       454       455       456 
109.96835 147.36813 152.39432 149.86401 106.21055 163.41078 168.27444 155.85423 
      457       458       459       460       461       462       463       464 
136.78099 204.50110 115.72090 166.82063 113.56614 123.34751 136.70975 143.39951 
      465       466       467       468       469       470       471       472 
135.34580  98.44458 164.99800 163.75184 158.33794 149.70401 146.75652 149.65797 
      473       474       475       476       477       478       479       480 
201.56434 160.68342 144.82817 147.41448 113.52576 191.18718 144.53477 145.80859 
      481       482       483       484       485       486       487       488 
145.64267 181.73417 141.61701 149.51494 132.31808 167.51278 128.26862 132.21064 
      489       490       491       492       493       494       495       496 
 94.26651 181.22267 139.62648 196.96431 131.21919  86.09835 159.41616 199.98189 
      497       498       499       500       501       502       503       504 
118.21873 127.61573 189.53638 160.71170 108.63548 137.19988 117.61193 115.58129 
      505       506       507       508       509       510       511       512 
181.74385 153.85581 111.85147 129.21202 127.75988 125.59242 156.39825 122.05988 
      513       514       515       516       517       518       519       520 
130.68281 168.16906 153.41066 145.22976  92.58597 162.04743 111.33337 108.24769 
      521       522       523       524       525       526       527       528 
167.66315 121.18656 149.18143 210.13095 183.02837 140.53427 146.56573 144.87310 
      529       530       531       532       533       534       535       536 
166.49509 122.59210 150.75937 125.61078  86.18543 102.22212 155.43198 148.15748 
      537       538       539       540       541       542       543       544 
149.35042 211.70608 166.89867 163.01990 165.98605 131.55750 139.05699 136.26600 
      545       546       547       548       549       550       551       552 
187.37512 209.16296 124.24118 217.15732 131.45206 200.44739 161.97900 211.75724 
      553       554       555       556       557       558       559       560 
196.60627 158.87603 146.42271 158.66215  94.57544 130.58982 219.83518 168.73653 
      561       562       563       564       565       566       567       568 
103.23676 138.61184 139.28506  90.38635 107.43178 145.56665 182.75359  84.66830 
      569       570       571       572       573       574       575       576 
 95.54172 110.40895 141.69131 149.70431 155.93306 147.90934  66.92172 147.40374 
      577       578       579       580       581       582       583       584 
164.29821 101.57863 140.66876 128.56197 180.70434 152.35734  98.03817 120.94437 
      585       586       587       588       589       590       591       592 
163.93671 103.51459 234.60747 183.02836 112.99979 126.88485 117.09249 197.43122 
      593       594       595       596       597       598       599       600 
189.30520 199.85646 204.25296 116.47294 133.09952 159.90792  94.78936 146.62481 
      601       602       603       604       605       606       607       608 
161.30100 206.37377 171.43030 102.88773 109.65036 109.00625 133.92054 119.10930 
      609       610       611       612       613       614       615       616 
133.56496 161.88262 215.55343 143.80112 137.94141 115.89952 171.28105 124.59056 
      617       618       619       620       621       622       623       624 
125.53644 117.37452 116.79146 120.18302 111.49305 145.67830 169.56072 142.96825 
      625       626       627       628       629       630       631       632 
199.42203 178.96055 179.89291 127.84212 168.28382 170.12228 174.47724 209.10902 
      633       634       635       636       637       638       639       640 
150.86026  98.97987 166.86275 142.15511 157.93122 133.83970 189.96146 181.17574 
      641       642       643       644       645       646       647       648 
117.20864 128.77141  88.50434 140.26888 113.20755 159.03742  93.20243 205.15286 
      649       650       651       652       653       654       655       656 
156.19785  93.57605 152.34148 167.76096 111.57876 156.65744 179.34831 116.69196 
      657       658       659       660       661       662       663       664 
137.27616 138.71104 106.39228 174.14174 136.91016 131.00698 157.96093 144.11312 
      665       666       667       668       669       670       671       672 
149.95415  97.68463  83.63646 140.30589 184.32985 101.12046 198.48657 141.59381 
      673       674       675       676       677       678       679       680 
122.32839 132.94777 189.39847 193.85573 140.69053 128.54644 123.63920 174.14799 
      681       682       683       684       685       686       687       688 
 76.07789 142.56740 142.26049 103.90995 153.78283 184.23997 169.68028 163.73493 
      689       690       691       692       693       694       695       696 
153.14078 214.91104 209.38485 187.78498 190.32461 203.45085 132.04024 147.59594 
      697       698       699       700       701       702       703       704 
209.54622 152.67528 149.49657 119.85993 158.63245 193.95325 157.32780  74.61815 
      705       706       707       708       709       710       711       712 
139.78303 148.86800 170.62168 177.30972 141.46807 165.29557  85.14906 195.68289 
      713       714       715       716       717       718       719       720 
 94.31627 174.03493  92.89663 124.01311 175.83164 101.39999 147.03294 142.49622 
      721       722       723       724       725       726       727       728 
102.47200 160.55174 153.39793 179.41667 161.80378 188.13850 170.92407 181.38065 
      729       730       731       732       733       734       735       736 
183.05153 109.29652 206.81269 107.39169 149.97108 115.57644 137.92279 112.17761 
      737       738       739       740       741       742       743       744 
161.60959 123.38311 102.45505 121.23915 148.07805 104.21889 101.91801 104.84263 
      745       746       747       748       749       750       751       752 
159.82396 145.34680 184.67126 149.98669 204.25467 127.65413 135.43458 188.38210 
      753       754       755       756       757       758       759       760 
111.04171 163.76741 106.66981 187.99267 170.43716 131.38677 196.23994 158.66072 
      761       762       763       764       765       766       767       768 
117.32960 116.56648  95.92667 204.91089 178.29951 170.92889 167.34383 117.10943 
      769       770       771       772       773       774       775       776 
166.87970 175.31637 151.84175 133.86458 147.68267 183.06057 139.74572 191.49750 
      777       778       779       780       781       782       783       784 
157.37761 206.26633 160.58114 188.55907 155.08604 158.00274 169.29532 130.42954 
      785       786       787       788       789       790       791       792 
117.71002 110.82296 115.95208 131.84435 160.53279 157.60878 137.71198 207.13405 
      793       794       795       796       797       798       799       800 
111.15026 134.09405 191.88358 143.70642 182.39076 123.30742 135.25593 159.66430 
      801       802       803       804       805       806       807       808 
137.93381 148.97340 126.11531  96.50831 122.65395 161.04010 182.92128 115.70395 
      809       810       811       812       813       814       815       816 
124.13266 130.35385 107.80088 109.31520 150.02567 165.23199 107.83846 208.98325 
      817       818       819       820       821       822       823       824 
191.25359 132.38617 132.99406 124.38528 190.38509 168.24510 144.47013 186.40262 
      825       826       827       828       829       830       831       832 
193.52193 199.05886 189.04803 165.37642 227.71931 181.57172 194.40629 114.47539 
      833       834       835       836       837       838       839       840 
126.94223 173.55531 173.64069  86.12804 158.79830 159.37572 114.80716 126.70284 
      841       842       843       844       845       846       847       848 
133.02065 131.38989  69.92034 133.43639 115.30965 174.83223 117.28155 215.16084 
      849       850       851       852       853       854       855       856 
115.09295 118.63449 149.71050  98.83716 137.78178 157.02373 181.20713 147.35541 
      857       858       859       860       861       862       863       864 
135.67820 162.41962 122.64183 166.25939 165.39337 173.02002 142.67348 118.10370 
      865       866       867       868       869       870       871       872 
121.27506 156.76180 102.17407 112.04873 161.54260 146.19527 151.90878  98.57488 
      873       874       875       876       877       878       879       880 
148.95197 141.54518 144.79879 135.99896 220.22154 166.94160 170.91508 134.34702 
      881       882       883       884       885       886       887       888 
140.27201 149.00314 181.41794 186.38880 112.23641 137.02320 150.14489 153.80293 
      889       890       891       892       893       894       895       896 
133.78237 177.00591  97.29345 177.82945 108.96474 143.77484 109.88781 137.99429 
      897       898       899       900       901       902       903       904 
195.43959 133.20663 165.10963  98.74387 102.76223 183.61170 249.30085 178.79915 
      905       906       907       908       909       910       911       912 
147.14736  82.47596 201.46996 151.11012 134.65252  92.85790 122.84505 139.48203 
      913       914       915       916       917       918       919       920 
179.77475 171.35085 173.99905 212.88938 125.60796 177.90413 165.16701 166.47500 
      921       922       923       924       925       926       927       928 
114.76052 135.98509 107.74073 168.20780 207.28439 128.85987 173.56322 125.16145 
      929       930       931       932       933       934       935       936 
 92.67335 162.16668 206.59530 187.35367 164.60405 159.80983 128.72787 169.05167 
      937       938       939       940       941       942       943       944 
129.30531 113.91941 116.44077 147.14597 116.33535 198.55777 135.72938 161.85915 
      945       946       947       948       949       950       951       952 
168.73342 165.43831 113.07268 173.07630  97.41609 163.47127 163.04448 178.74035 
      953       954       955       956       957       958       959       960 
161.54741 110.63222 185.37558 155.14032  81.43196 121.41604 168.27137 116.81465 
      961       962       963       964       965       966       967       968 
162.30799 128.27654 181.95155 106.08367 203.26144 124.03628 187.93702 158.60301 
      969       970       971       972       973       974       975 
 82.05091 167.86634 193.10652 144.21857 166.81020 154.91225 184.98919 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gvlma)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gvlma</span>(my.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Final ~ Yr1 + Yr2 + Yr3, data = ugtests)

Coefficients:
(Intercept)          Yr1          Yr2          Yr3  
   14.14599      0.07603      0.43129      0.86568  


ASSESSMENT OF THE LINEAR MODEL ASSUMPTIONS
USING THE GLOBAL TEST ON 4 DEGREES-OF-FREEDOM:
Level of Significance =  0.05 

Call:
 gvlma(x = my.lm) 

                      Value   p-value                   Decision
Global Stat        54.24704 4.672e-11 Assumptions NOT satisfied!
Skewness            0.73224 3.922e-01    Assumptions acceptable.
Kurtosis            0.06324 8.015e-01    Assumptions acceptable.
Link Function      53.43397 2.675e-13 Assumptions NOT satisfied!
Heteroscedasticity  0.01759 8.945e-01    Assumptions acceptable.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(visreg)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">visreg</span>(my.lm, <span class="at">xvar=</span><span class="st">"Yr2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>